CREATE TABLE IF NOT EXISTS public.company1
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 99999999),
    address character varying(255),
    name character varying(255),
    nit character varying(255),
    phone character varying(255),
    CONSTRAINT company_pkey PRIMARY KEY (id),
    CONSTRAINT uk_nit UNIQUE (nit)
)
